services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    environment: 
      - PORT=3001
    networks:
     - my_network  

networks:
  my_network:
    external: true
