# tradeport-frontend/k8s/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: tradeport-frontend-secrets
  namespace: ui-namespace
  labels:
    app: tradeport-frontend
    component: frontend
    service: ui
    version: v1
type: Opaque
data:
  # Base64 encoded values - replace with actual encoded secrets
  # To encode: echo -n "your-secret" | base64 
  
  # API Keys
  api_key: eW91ci1hcGkta2V5LWZvci1mcm9udGVuZA==  # 'your-api-key-for-frontend' base64 encoded
  
  # Third-party service keys
  google_analytics_key: Z29vZ2xlLWFuYWx5dGljcy1rZXktZm9yLWZyb250ZW5k  # 'google-analytics-key-for-frontend' base64 encoded
  recaptcha_secret: cmVjYXB0Y2hhLXNlY3JldC1mb3ItZnJvbnRlbmQ=  # 'recaptcha-secret-for-frontend' base64 encoded
  
  # Session and security secrets
  session_secret: dHJhZGVwb3J0LXNlc3Npb24tc2VjcmV0LWZyb250ZW5k  # 'tradeport-session-secret-frontend' base64 encoded
  csrf_token_secret: Y3NyZi10b2tlbi1zZWNyZXQtZnJvbnRlbmQ=  # 'csrf-token-secret-frontend' base64 encoded
  
stringData:
  # Non-sensitive configuration that can be plain text
  # app_version: "1.0.0"
  # build_number: "001"