# ======================================================
# Continuous Deployment (CD) Workflow - Stage 1
# ======================================================
# This workflow builds and deploys the Tradeport frontend
# application to Docker Hub with the following features:
#
# - Environment-specific deployments (dev/prod)
# - Automatic versioning from package.json
# - Multi-tag Docker images for different purposes
# - Verification steps to confirm successful deployment
# - Health check of the deployed application
#
# The workflow runs automatically after CI pipeline completes,
# and can also be manually triggered with environment selection.
# ======================================================

name: "CI Pipeline - Deploy Tradeport Frontend to Dockerhub"

on:
  workflow_run:
    workflows: ["CI Pipeline - TradePort Frontend"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

env:
  DOCKERHUB_IMAGE_FRONTEND: prabhulalithakrishnan/tradeport-frontend
  REMOTE_DIR: /root/tradeport

jobs:
  prepare:
    name: ⛏️ Prepare Environment
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set-outputs.outputs.version }}
      short_sha: ${{ steps.set-outputs.outputs.short_sha }}
      env_name: ${{ steps.set-outputs.outputs.env_name }}
    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 🏷️ Determine version and set outputs
        id: set-outputs
        run: |
          VERSION=$(grep '"version"' ./package.json | cut -d'"' -f4 || echo ${GITHUB_SHA::8})
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "short_sha=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
          echo "env_name=prod" >> $GITHUB_OUTPUT

      - name: 📤 Upload .env file
        uses: actions/upload-artifact@v4
        with:
          name: env-file
          path: .env
          retention-days: 1
          if-no-files-found: warn

  build:
    name: 🏗️ Build Frontend Image
    if: success()
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 🌍 Set environment-specific variables
        run: |
          echo "VITE_API_URL=${{ secrets.PROD_API_URL }}" >> .env
          echo "Using environment variables:"
          cat .env | sed 's/\(.*SECRET.*=\).*/\1********/'

      - name: 🐳 Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: 🐳 Build and tag Frontend Image
        run: |
          DOCKERFILE=./Dockerfile.prod
          docker build -t ${{ env.DOCKERHUB_IMAGE_FRONTEND }}:latest \
                       -t ${{ env.DOCKERHUB_IMAGE_FRONTEND }}:${{ needs.prepare.outputs.version }} \
                       -t ${{ env.DOCKERHUB_IMAGE_FRONTEND }}:${{ needs.prepare.outputs.short_sha }} \
                       -t ${{ env.DOCKERHUB_IMAGE_FRONTEND }}:${{ needs.prepare.outputs.env_name }} \
                       -f $DOCKERFILE .

      - name: 🐳 Push Frontend Image to Docker Hub
        run: |
          docker push ${{ env.DOCKERHUB_IMAGE_FRONTEND }}:latest
          docker push ${{ env.DOCKERHUB_IMAGE_FRONTEND }}:${{ needs.prepare.outputs.version }}
          docker push ${{ env.DOCKERHUB_IMAGE_FRONTEND }}:${{ needs.prepare.outputs.short_sha }}
          docker push ${{ env.DOCKERHUB_IMAGE_FRONTEND }}:${{ needs.prepare.outputs.env_name }}

  verify:
    name: 🔍 Verify Docker Hub Push
    if: success()
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 🔍 Verify Docker Hub Push
        run: |
          echo "Verifying image push to Docker Hub..."
          docker pull ${{ env.DOCKERHUB_IMAGE_FRONTEND }}:latest && \
            echo "✅ Successfully verified image push to Docker Hub" || \
            (echo "❌ Failed to verify image on Docker Hub" && exit 1)

  health-check:
    name: ❤️‍🩹 Health Check
    if: success()
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - name: 🔍 Health check
        run: |
          sleep 20
          curl -m 10 -sSf http://${{ secrets.DROPLET_IP }}:3001/health || \
          curl -m 10 -sSf http://${{ secrets.DROPLET_IP }}:3001 || \
          echo "Frontend may still be starting up, please verify manually"
