name: "Security Scan - SAST & SCA"

on:
  # Only run on PRs to main and pushes to main or feature branches to save GitHub Actions minutes
  push:
    branches: [main, "feature/**"]
  pull_request:
    branches: [main]
  # Allow manual triggering
  workflow_dispatch:

# Limit concurrent runs to save resources on personal account
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security-scan:
    runs-on: ubuntu-latest
    # Set timeout to prevent excessive usage on personal account
    timeout-minutes: 15
    permissions:
      actions: read
      contents: read
      security-events: write # For GitHub security dashboard integration

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Install Dependencies
        run: npm ci --prefer-offline --no-audit

      # --- Use GitHub's native CodeQL for SAST (more efficient than CLI) ---
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript, typescript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:javascript"

      # --- Lightweight SCA using npm audit ---
      - name: Run npm audit for dependencies
        run: npm audit --json > npm-audit.json || true

      - name: Check for high severity vulnerabilities
        run: |
          if grep -q '"severity":"high"' ./npm-audit.json; then
            echo "⚠️ High severity vulnerabilities found in dependencies"
            echo "Review npm-audit.json for details (but won't fail the build)"
          fi

      # --- Archive Reports ---
      - name: Archive security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            ./npm-audit.json
          retention-days: 7 # Shorter retention to save space
