name: "CI - Stage-2 - Security Scan - SAST & SCA"

on:
  # Only run on PRs to main and pushes to main or feature branches to save GitHub Actions minutes
  push:
    branches: [main, "feature/**"]
  pull_request:
    branches: [main]
  # Allow manual triggering
  workflow_dispatch:

# Limit concurrent runs to save resources on personal account
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      actions: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Install Dependencies
        run: npm ci --prefer-offline --no-audit

      # --- SAST with CodeQL CLI (no GHAS required) ---
      - name: Download CodeQL CLI
        run: |
          wget https://github.com/github/codeql-cli-binaries/releases/download/v2.14.5/codeql-linux64.zip
          unzip codeql-linux64.zip -d codeql

      - name: Create CodeQL database
        run: |
          mkdir codeql-db
          ./codeql/codeql/codeql database create codeql-db --language=javascript --source-root=.

      - name: Analyze with CodeQL and generate SARIF
        run: |
          mkdir -p results
          ./codeql/codeql/codeql database analyze codeql-db \
            javascript-code-scanning.qls \
            --format=sarif-latest \
            --output=results/javascript.sarif || true

      # --- Lightweight SCA using npm audit ---
      - name: Run npm audit for dependencies
        run: npm audit --json > npm-audit.json || true

      - name: Check for high severity vulnerabilities
        run: |
          if grep -q '"severity":"high"' ./npm-audit.json; then
            echo "⚠️ High severity vulnerabilities found in dependencies"
            echo "Review npm-audit.json for details (but won't fail the build)"
          fi

      # --- Archive Reports ---
      - name: Archive security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            ./npm-audit.json
            ./results/javascript.sarif
          retention-days: 7
