name: "CI-Stage-2-SAST-and-SCA-Scan"

on:
  push:
    branches: [main, develop, githubcicd, "feature/**"]
  pull_request:
    branches: [main, develop]

jobs:
  sast:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache-nodemodules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm ci --legacy-peer-deps

      # --- OWASP Dependency Check (SCA) ---
      - name: OWASP Dependency Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v7.2.0/dependency-check-7.2.0-release.zip
          unzip dependency-check-7.2.0-release.zip

      - name: Run scan with ODC
        run: |
          dependency-check/bin/dependency-check.sh --project "TradePort" --scan . --format XML --out odc-report.xml || true
          dependency-check/bin/dependency-check.sh --project "TradePort" --scan . > ODC-report || true

      - name: Check for critical vulnerabilities
        run: |
          if grep -q "CRITICAL" ./ODC-report; then
            echo "Critical vulnerabilities found"
            grep "CRITICAL" ./ODC-report
            exit 1
          fi

      # --- CodeQL (SAST) ---
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Autobuild (for Node-based projects)
        uses: github/codeql-action/autobuild@v2

      - name: Run CodeQL Analysis
        run: |
          mkdir -p results
          codeql database analyze --format=sarif-latest \
            --output=results/javascript.sarif \
            /github/workspace/codeql-database \
            javascript-code-scanning.qls || true

      # --- Archive Reports ---
      - name: Archive security reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            ./ODC-report
            ./odc-report.xml
            ./results/javascript.sarif
